### ISSUE TITLE
Circular Dependency warning

### ISSUE THREAD

**Issue by esgabo** [PaulMaly/svelte-content-loader#2]
I have this warning appearing.

(!) Circular dependency
node_modules\svelte-content-loader\src\index.js -> node_modules\svelte-content-loader\src\TableLoader.svelte -> node_modules\svelte-content-loader\src\index.js

I'm not sure if this was noticed before and if there's any plan to rearrange dependency to get rid of it.

**Comment by esgabo** [comment]
I have created a PR addressing this issue
https://github.com/PaulMaly/svelte-content-loader/pull/3

**Comment by PaulMaly** [comment]
Thanks!
